language: node_js
cache:
  directories:
  - node_modules 
before_deploy: |-
  echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null  
jobs:
   include:
    # Define the release stage that publishes lerna to npm
    - stage: release
      node_js:
       - 10
       - 12
      deploy:
          on:
            branch: master
            condition: $TRAVIS_COMMIT_MESSAGE =~ ^chore\(release\):\ (0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
          provider: script
          skip_cleanup: true 
          script:
           - npm run lerna:publish          