language: node_js
node_js:
  - 10
  - 12
cache:
  directories:
  - node_modules
before_deploy:
  echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
  echo $TRAVIS_COMMIT_MESSAGE
  export TAG=$'v'$TRAVIS_COMMIT_MESSAGE
jobs:
  include:
    # Define the release stage that publishes lerna to npm
    - stage: release
      deploy:
          on:
            branch: master
          provider: script
          skip_cleanup: true
          script:
           - npm run lerna:deploy -- $TRAVIS_COMMIT_MESSAGE
