language: node_js
cache:
  directories:
  - node_modules 
before_deploy: |-
  echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
jobs:
   include:
    # Define the release stage that publishes lerna to npm
    - stage: release
      node_js:
       - 10
       - 12
      deploy:
          on:
            branch: master
            env:
            - TRAVIS_COMMIT_MESSAGE = $TRAVIS_COMMIT_MESSAGE
          provider: script
          skip_cleanup: true 
          script:
           - npm run check-version         