  
language: node_js
jobs:
   include:
    # Define the release stage that publishes lerna to npm
    - stage: release
       cache:
        directories:
        - node_modules
        node_js:
          - 10
          - 12
        deploy:
          on:
            branch: master
            tags: true
            provider: script
            script: "npm run lerna:publish"
            skip_cleanup: true