name: One App Release Pull Request
on:
  push:
    branches: master
  repository_dispatch:
    types: [prepare-release-command]
jobs:
  prepare:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"
  release:
    needs: prepare
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: NODE_ENV=development npm ci
      - name: versioning
        run: |
          NODE_ENV=development npm ci
          git config --local user.email "one.amex@aexp.com"
          git config --local user.name "nellyk"
          npm run lerna:version 
      - name: Create release pull request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.PA_TOKEN }}
          commit-message: One App Prepare Release
          committer: 'OneAmexBot <one.amex@aexp.com>'
          author: 'OneAmexBot <one.amex@aexp.com>'
          title: 'One App Prepare Release'
          body: 'This is an auto-generated pull request for One App release changes. Please review this PR and merge it for a release to be initiated. Please close this PR to stop a release from being initiated.'
          labels: release,automated pr,skip-release-drafter
          branch: prepare-release
          base: master
