name: Release
on:
  repository_dispatch:
    types: [lerna_release]
jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: NODE_ENV=development npm ci 
      - name: Lerna release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run lerna:publish
